services:
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: apache/kafka
    ports:
      - 9092:9092
    links:
      - "zookeeper:zookeeper"
  mysql:
    image: mysql:8.4
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: debezium
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw
    volumes:
      - type: volume
        source: mysql8-4
        target: /var/lib/mysql
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
  connect:
    image: quay.io/debezium/connect:3.0
    ports:
      - 8083:8083
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
    links:
      - "kafka:kafka"
      - "mysql:mysql"


volumes:
  mysql8-4: