global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.qq.com:465'
  smtp_from: ${SendFrom}
  smtp_auth_username: ${SendFrom}
  smtp_auth_password: ${AuthCode}
  smtp_require_tls: false

route:
  group_by: [ 'alertname' ]
  group_wait: 30s
  repeat_interval: 1h
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
      - to: ${SendTo}
        send_resolved: true
        html: |
          <h3>告警信息</h3>
          <p><strong>级别：</strong>{{ .Labels.severity }}</p>
          <p><strong>告警名称：</strong>{{ .Labels.alertname }}</p>
          <p><strong>描述：</strong>{{ .Annotations.description }}</p>
          <p><strong>时间：</strong>{{ .StartsAt }}</p>
          <p><strong>详情链接：</strong><a href="{{ .GeneratorURL }}">查看Prometheus</a></p>