services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9400:9090"
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - type: bind
        source: ./rules
        target: /etc/prometheus/rules
      - type: volume
        source: prometheus-data
        target: /prometheus
    depends_on:
      - cadvisor
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    volumes:
      - type: volume
        source: grafana-storage
        target: /var/lib/grafana
    environment:
      GF_LOG_LEVEL: debug
  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - type: bind
        source: ./alertmanager.yml
        target: /etc/alertmanager/alertmanager.yml
volumes:
  prometheus-data:
  grafana-storage:

